#test
# Circle CI version
version: 2

# Reference small tasks or commands to re-use them in multiple jobs
references:
  # Configure the base image to run the jobs in
  setup_container_tests: &setup_container_tests
    docker:
      - image: circleci/node:10.10.0    #node:10.10.0-browser
    working_directory: /Users/birol/circletest

  setup_container: &setup_container
    docker:
      - image: circleci/node:10.10.0
    working_directory: ~/repo       #~/repo

# Each job is run in its own container
# One task / pipline step per job is a good policy 
jobs:

  # This job runs setup tasks
  # e.g. npm install, composer install, gradle build (?)
  setup:
    <<: *setup_container
    steps:
      - checkout # circle ci specific command to check out the current commit
      - run:
          name: Install dependencies
          command: npm install # runs a shell command
      - persist_to_workspace:
          root: ~/repo
          paths: ./*

  # This job runs our (unit) tests
  test:
    <<: *setup_container_tests
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run test

  # This job builds our application
  build:
    <<: *setup_container
    steps:
      - run: npm run build  

  # This job deploys our application
  deploy:
    <<: *setup_container
    steps:
      - run: ./deploy.sh

# Here we define our pipelines for different branches / tags
workflows:
  version: 2
  # This workflow is triggered for all pushes
  pull_request:
    jobs:
      - setup:
          filters:
            branches:
              ignore:
                - master
      - test:
          requires:
            - setup
  # This workflow is triggered for push events on the master branch
  release:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - master
      - test:
          requires:
            - setup
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
  

#Sample .yml File - von der https://circleci.com/setup-project/gh/efebirol/ci-cd-test Seite - "Linux -> Node" ausgewählt 

# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

# version: 2
# jobs:
#   build:
#     docker:
#       # specify the version you desire here
#       - image: circleci/node:7.10
      
#       # Specify service dependencies here if necessary
#       # CircleCI maintains a library of pre-built images
#       # documented at https://circleci.com/docs/2.0/circleci-images/
#       # - image: circleci/mongo:3.4.4

#     working_directory: ~/repo

#     steps:
#       - checkout

#       # Download and cache dependencies
#       - restore_cache:
#           keys:
#           - v1-dependencies-{{ checksum "package.json" }}
#           # fallback to using the latest cache if no exact match is found
#           - v1-dependencies-

#       - run: yarn install

#       - save_cache:
#           paths:
#             - node_modules
#           key: v1-dependencies-{{ checksum "package.json" }}
        
#       # run tests!
#       - run: yarn test
